/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.coffee.category;

import com.app.coffee.Login.Register.ListUsers;
import com.app.coffee.bill.Bill;
import com.app.coffee.dashboard.DashboardPage;
import com.app.coffee.employee.EmployeeManager;
import com.app.coffee.menu.MenuPanel;

import java.awt.CardLayout;

/**
 *
 * @author anhso
 */
public class CategoryForm extends javax.swing.JPanel {

    /**
     * Creates new form CategoryForm
     */
    public CategoryForm() {
        initComponents();
        loadPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CategoryPanel01 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CategoryTable = new javax.swing.JTable();
        CategoryFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DeleteCategory = new javax.swing.JButton();
        AddCategoryButton = new javax.swing.JButton();
        EditCategoryButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Category Manager");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(1344, 718));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CategoryPanel01.setBackground(new java.awt.Color(255, 255, 255));
        CategoryPanel01.setLayout(new java.awt.BorderLayout());

        CategoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Category_name", "description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CategoryTable.setRowHeight(30);
        jScrollPane1.setViewportView(CategoryTable);
        if (CategoryTable.getColumnModel().getColumnCount() > 0) {
            CategoryTable.getColumnModel().getColumn(0).setMinWidth(80);
            CategoryTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            CategoryTable.getColumnModel().getColumn(0).setMaxWidth(100);
            CategoryTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            CategoryTable.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        CategoryPanel01.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(CategoryPanel01, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 800, 520));

        CategoryFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        CategoryFormPanel.setLayout(new java.awt.CardLayout());
        jPanel3.add(CategoryFormPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 430, 520));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Category Table :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Category Form :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 120, 30));

        DeleteCategory.setBackground(new java.awt.Color(102, 102, 102));
        DeleteCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeleteCategory.setForeground(new java.awt.Color(255, 255, 255));
        DeleteCategory.setText("Delete");
        jPanel3.add(DeleteCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 90, 30));

        AddCategoryButton.setBackground(new java.awt.Color(255, 102, 0));
        AddCategoryButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddCategoryButton.setForeground(new java.awt.Color(255, 255, 255));
        AddCategoryButton.setText("Add");
        AddCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCategoryButtonActionPerformed(evt);
            }
        });
        jPanel3.add(AddCategoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 90, 30));

        EditCategoryButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EditCategoryButton.setForeground(new java.awt.Color(255, 102, 0));
        EditCategoryButton.setText("Edit");
        EditCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCategoryButtonActionPerformed(evt);
            }
        });
        jPanel3.add(EditCategoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCategoryButtonActionPerformed
        showPanel("addCategory");
    }//GEN-LAST:event_AddCategoryButtonActionPerformed

    private void EditCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCategoryButtonActionPerformed
         showPanel("editCategory");
    }//GEN-LAST:event_EditCategoryButtonActionPerformed
     private void loadPanels() {
        AddCategory addCategory = new AddCategory();
        EditCategory editCategory = new EditCategory();
        CategoryFormPanel.add(addCategory,"addCategory");
        CategoryFormPanel.add(editCategory,"editCategory");
    }
   private void showPanel(String panelName) {
        ((CardLayout)CategoryFormPanel.getLayout()).show(CategoryFormPanel, panelName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCategoryButton;
    private javax.swing.JPanel CategoryFormPanel;
    private javax.swing.JPanel CategoryPanel01;
    private javax.swing.JTable CategoryTable;
    private javax.swing.JButton DeleteCategory;
    private javax.swing.JButton EditCategoryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
