/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.coffee.Login.LoginAccount;
import com.app.coffee.Backend.DAO.UserDAO;
import com.app.coffee.Backend.Model.UsersModel;
import com.app.coffee.Database.PasswordUtils;
import com.app.coffee.Login.CustomDialog;
import com.app.coffee.virtualKeyBoard.LetterVirtualKeyBoard;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
/**
 *
 * @author Admin
 */
public class RegisterAdmin extends javax.swing.JPanel {
    private String user;
    private LetterVirtualKeyBoard virtualKeyboard;
    private JDialog keyboardDialog;
    /**
     * Creates new form RegisterAdmin
     */
    public RegisterAdmin(String email) {
        initComponents();
        this.user = email;
        
        virtualKeyboard = new LetterVirtualKeyBoard();
        keyboardDialog = new JDialog((java.awt.Frame) SwingUtilities.getWindowAncestor(this), "Virtual Keyboard", true);
        keyboardDialog.add(virtualKeyboard);
        keyboardDialog.pack();
        keyboardDialog.setLocationRelativeTo(null);

        TxtResetPassword.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                showVirtualKeyboard(TxtResetPassword);
            }
        });

        TxtVerResetPassword.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                showVirtualKeyboard(TxtVerResetPassword);
            }
        });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtResetPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        TxtVerResetPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(243, 114, 44)));
        jPanel3.setForeground(new java.awt.Color(51, 255, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(73, 80, 87));
        jLabel3.setText("Register Admin");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(73, 80, 87));
        jLabel4.setText("New Password :");

        TxtResetPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(73, 80, 87));
        jLabel5.setText("Confirm Password :");

        TxtVerResetPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TxtVerResetPassword.setVerifyInputWhenFocusTarget(false);

        jButton2.setBackground(new java.awt.Color(243, 114, 44));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(TxtVerResetPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(TxtResetPassword))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(112, 112, 112))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtResetPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtVerResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (TxtResetPassword.getText().isEmpty() || TxtVerResetPassword.getText().isEmpty()) {
            new CustomDialog(null, "Error", "Please enter both new password and confirm password");
            return;
        }

        if (!TxtResetPassword.getText().equals(TxtVerResetPassword.getText())) {
            new CustomDialog(null, "Error", "Passwords do not match");
            return;
        }

        String email = user;

        try {
            UserDAO userDAO = new UserDAO();
            UsersModel admin = new UsersModel();
            admin.setEmail(email);
            admin.setPassword(TxtResetPassword.getText());

            int result = userDAO.Create(admin);

            if (result > 0) {
                new CustomDialog(null, "Success", "Admin account created successfully");
                displayLoginForm();
            } else {
                new CustomDialog(null, "Error", "Failed to create admin account");
            }

        } catch (Exception ex) {
            new CustomDialog(null, "Error", "Failed to create admin account: " + ex.getMessage()); 
            ex.printStackTrace();
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void displayLoginForm() {
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }
    
     private void showVirtualKeyboard(JPasswordField passwordField) {
        virtualKeyboard.setText(new String(passwordField.getPassword()));
        virtualKeyboard.setTitle("Virtual Keyboard");
        keyboardDialog.setVisible(true);
        passwordField.setText(virtualKeyboard.getSavedText());
    }

    private void showVirtualKeyboard(JTextField textField) {
        virtualKeyboard.setText(textField.getText());
        virtualKeyboard.setTitle("Virtual Keyboard");
        keyboardDialog.setVisible(true);
        textField.setText(virtualKeyboard.getSavedText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TxtResetPassword;
    private javax.swing.JPasswordField TxtVerResetPassword;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
